In [29]:
import numpy as np
import pandas as pd 
from sklearn.preprocessing import LabelEncoder

#### Description
Create another feature based called **BMI_group** which groups people based on their **BMI**. The groups should be as follows:<br>
**Underweight**: BMI is less than 18.5.<br>
**Normal**: BMI is 18.5 to 24.9.<br>
**Overweight**: BMI is 25 to 29.9.<br>
**Obese**: BMI is 30 or more.<br>
The grouping is based on WHO standards.<br>

The output should have first five rows of the resulting dataframe.

In [3]:
df=pd.read_csv("insurance.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [4]:
bins = [0, 18.5, 25.0, 30.0, 200]
slot = ["Underweight", "Normal",'Overweight', "Obese"]
df["BMI_group"] = pd.cut(df["bmi"], bins, labels=slot)
df.head()

   age     sex     bmi  children smoker     region      charges   BMI_group
0   19  female  27.900         0    yes  southwest  16884.92400  Overweight
1   18    male  33.770         1     no  southeast   1725.55230       Obese
2   28    male  33.000         3     no  southeast   4449.46200       Obese
3   33    male  22.705         0     no  northwest  21984.47061      Normal
4   32    male  28.880         0     no  northwest   3866.85520  Overweight

In [5]:
le = LabelEncoder()
df.sex = le.fit_transform(df.sex)
df.BMI_group = le.fit_transform(df.BMI_group)
df.smoker = le.fit_transform(df.smoker)
df.region = le.fit_transform(df.region)
df.head()

   age  sex     bmi  children  smoker  region      charges  BMI_group
0   19    0  27.900         0       1       3  16884.92400          2
1   18    1  33.770         1       0       2   1725.55230          1
2   28    1  33.000         3       0       2   4449.46200          1
3   33    1  22.705         0       0       1  21984.47061          0
4   32    1  28.880         0       0       1   3866.85520          2

In [6]:
print(df[['smoker', 'bmi']].corr()['smoker'][1])
print(df[['smoker', 'age']].corr()['smoker'][1])
print(df[['smoker', 'charges']].corr()['smoker'][1])

0.003750425904980336
-0.02501875153628481
0.7872514304984697

In [40]:
# Read training data
train = pd.read_csv("insurance_training.csv")
train = train.fillna(method='ffill')
# Read test data
test = pd.read_csv("insurance_test.csv")

In [44]:
from sklearn.linear_model import LinearRegression

X_train_lm = train.drop('charges', axis=1).values
y_train_lm = train['charges'].values
lm = LinearRegression()

lm.fit(X_train_lm, y_train_lm)

y_test_pred = lm.predict(test)

In [45]:
y_test_pred

array([ 8601.50473149,  7274.0550904 , 36650.25371263,  9461.54577199,
       26838.88000245, 11214.59490109,   746.9499201 , 17092.57028857,
         579.72239046, 10942.16587621, 28489.43359378,  9429.71984003,
        4679.2047214 , 38319.42074502, 40504.42895757, 37314.93027878,
       15365.14630871, 35978.44072843,  8766.60385558, 31252.30803423,
        4069.81000419, 10104.46153229,  2297.11224037,  6851.68116752,
       11221.45974852, 12920.74242631, 14651.27688438,  6109.69106861,
        9357.2435692 ,  2366.47613256,  8983.7468948 , 13236.3512562 ,
        4692.03994244,  4073.80666927,  4678.16136223, 13122.40336412,
        1410.05140545,  8712.04312702, 33967.50330118, 32375.92406848,
        3147.13427597,  4343.89811781, 14296.02834853, 11323.40414164,
        8739.55326901, 11507.11462267,  5053.56495766,  3598.8440298 ,
       35406.56241993,  9065.24732559, 15920.16977013,  1864.2208657 ,
       12547.47699634,  1393.06474673, 13820.60530594, 12710.48258577,
        3666.29915618, 32040.72005128, 13405.21614028, 12687.56956611,
       13959.85503956, 10580.08057571, 16432.1254753 ,  7298.29133631,
       12059.98782769,  3444.56268152, 26103.38666812, 10462.45718984,
        2784.56671493,  6341.70049089, 10438.50102638, 11483.11124632,
       11414.61131739,  9524.9480918 , 11886.23065216,  7800.69086979,
        7353.6279238 , 10335.32540199,  6499.92858134,  8630.25536103,
        3747.96035076, 36550.76624369,  5715.52869431, 30577.19338567,
       35156.98651277, 35060.3752999 ,  7127.82861822, 13082.40100608,
       10051.66608362, 14516.0551313 , 17604.28067651, 35732.29501317,
       32663.04630567,  5824.8461763 , 32320.08710862,  9806.46262016,
       29242.56130327,  3757.64491099, 29041.83038089,  6265.45994196,
        5238.66827707,  1176.76163125, 11617.71615579, 15098.15794915,
       12206.09792322,  4451.17253229,  9777.74166637, 32251.00028746,
         556.64881042, 32977.6146486 ,  3171.37579274, 10463.22246953,
       14585.67532041, 31275.49393275, 11308.62683341,  3703.61441313,
       12465.99465522, 31614.07506941,  7943.86497031,  3043.04979187,
        8396.37981384, 10756.48690272, 15096.02166124,  5573.3801449 ,
        4318.9677531 , 10141.56548608, 10897.84765168, 10933.30644064,
       14572.1614143 ,  7422.14193351,  5046.50169261,  9402.15697459,
        9682.29979642, 12263.96884692,  8109.12824378, 15638.40079715,
        8273.89243184, 31676.84884194, 35850.0786493 , 31654.77651747,
        5874.88962954, 12547.14428731,  6300.3998061 , 14633.68753728,
        1980.63191389, 32509.61920246,  6276.55279482,  4587.17458831,
       14733.33150552,  6795.81318449, 38958.18911496,  2882.50065552,
        6082.74648602, 31946.12612377, 11623.1229034 ,  8653.50513145,
       14951.62059296,  9507.56553364, 27154.27034736, 33306.97787571,
       14246.18742954,  1674.76248375, 12650.79798573,  2827.04523353,
        5648.09420638, 11980.68136867, 39558.93748784, 36288.81842577,
       33706.02870757,  4143.69693711,  7807.49022296,  8789.96294618,
       12686.72784091,  4841.07257234,  1890.44126402, 31622.07343144,
       24497.12346362, 17588.69674963, 25378.22864332, 10490.96456132,
       36630.55258773, -1393.17116544,  7225.2484064 ,  7555.59341365,
        4787.83091602,  4955.58040543,  5337.92705544,  3746.61270301,
       15512.91009418, 11053.47061524,  7003.45182039,  1994.87107332,
        1961.02864794, 31599.62000807, 16905.09460379, 12113.59313258,
        1710.51667907, 12330.05271974,   831.96975257,  8187.28036354,
        2572.07957246, 33439.46387293, 11061.80564119,  2476.32712276,
       25134.68757869, 26500.77111235,  9192.04952788,  2524.53900293,
       13573.66401797,  1791.68472541, 10736.09135794, 11065.55075397,
       16776.49467154, 26837.96659833,  6930.64022054,  4968.37181602,
        5514.95321856, 12724.57783694, 11303.02180655,  8601.90181844,
        4957.59110987, 12190.60701195, 13998.83768704, 35872.73726938,
        4529.38889524, 29214.25909487,  -232.83009528,  2932.76869078,
       11507.27652477, 15638.37090083,  5250.74169271,  5954.75083023,
        4461.43549049, 31214.74179572,  6773.18273591, 12676.18399675,
        5433.11095943,  9793.52458853, 36727.3816027 ,  4771.36825277,
        9073.91141018, 31165.50020528,  6144.32745669,  5264.02390247,
         646.86664078,  5222.08985744,  3976.03547849,  6720.30080596,
       18665.94965568, -2380.82137764,  2063.9250354 , 10488.41817991,
        2930.09384957, 10448.02053989,  3566.62525744,  5323.68353515,
       12061.03327134,  6623.48301   ,  8743.53757611,  7579.77734347,
        8301.51319345, 10822.89327688, 27539.67963655, 38907.52725015,
       11429.55770194,  7230.40299548, 40983.7022656 , 12416.08804102])